version: '2'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=9090"
      - "traefik.frontend.rule=Host:mon.diehlabs.lan"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090/tcp
    ports:
      - 9090:9090
    networks:
      - monitoring
    depends_on:
      - cadvisor

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    labels:
      - "traefik.enable=false"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '-collector.procfs=/host/proc -collector.sysfs=/host/sys -collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    expose:
      - 9100
    networks:
      - monitoring

  cadvisor:
    container_name: cadvisor
    image: cultclassik/cadvisor
    build: ./cadvisor
    restart: always
    labels:
      - "traefik.enable=false"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - "8080/tcp"
#    ports:
#      - 8086:8080
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:mon.diehlabs.lan"
    depends_on:
      - prometheus
    expose:
      - "3000/tcp"
    ports:
      - "3000:3000"
    volumes:
#      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/grafana:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - proxy
      - monitoring

networks:
  proxy:
    external:
      name: traefik_webgateway
  monitoring:
    driver: bridge
